### ISSUE TITLE
How can I get UCF png files?

### ISSUE THREAD

**Issue by 13052** [diptodip/counting#4]
Hi there,

I downloaded the UCF dataset, there are 50 .jpg and 50 .mat files, but where can I find or generate label .png files, quote from your README file: "_The label images should be named as ndots.png where n is the original image number. Once the label images are in data/UCF/B/, run the included blur.py in data/UCSD/B/ which will generate the ground truth density maps._ "

Thanks!

**Comment by diptodip** [comment]
I used  the ``get_ucf.sh`` script from the [HydraCNN repository](https://github.com/gramuah/ccnn) in order to get the data. That script runs

```
python tools/gen_ucf_dotmaps.py --notationdir data/UCF/params --imdir data/UCF/images
```

from the top level of the repository in order to generate the images. You can either look at that Python script and modify it to generate images if you don't want to redownload the data, or just run the full ``get_ucf.sh`` script and then simply move the images to the appropriate folder.

Hope this helps!

**Comment by 13052** [comment]
@diptodip thank you very much.
